### ISSUE TITLE
Trouble finding documentation

### ISSUE THREAD

**Issue by ajasja** [isambard-uob/isambard#2]
I'm having trouble finding the documentation for two common tasks:

- Running the tests after installation
- Configuring paths for external dependencies

I'm sure that used to be online already.
`import isambard;
isambard.settings.configure()`

no longer seems to work (and that info is in the [old repo on the wiki](https://github.com/woolfson-group/isambard/wiki/Quick-Start))

**Comment by ChrisWellsWood** [comment]
From ISAMBARD 2.0.0, `.isambard_settings` is no longer used. Any external dependencies simply have to be available on the path. As for the tests, they are no longer included in the packaged version of the code, if you want to run them:

1. Clone or download the repo.
1. Navigate to the downloaded module.
1. `pip install -e .` (`-e` symlinks the package so you can update code).
1. `pip install pytest`
1. `pytest` 

Let me know if you have any trouble.

**Comment by ajasja** [comment]
Thanks!

Well I get errors about hypothesis model not installed, but the tests do run.
![image](https://user-images.githubusercontent.com/19926/41539973-572be27e-730f-11e8-8919-f60be3d6fbd2.png)

**Comment by ChrisWellsWood** [comment]
Yeah, good point, there are some dependencies for the tests. Not sure if there are any others apart from `hypothesis`.

**Comment by ajasja** [comment]
Great, work fine!
