### ISSUE TITLE
Example analysis of antiparallel dimer

### ISSUE THREAD

**Issue by ajasja** [isambard-uob/isambard#5]
Do you have an example of analysing an antiparallel CC?
[Here](https://woolfson-group.github.io/isambard/tutorial/MakingModels.html) is a nice example for a parallel CC.

The pacc.py does say "that it works also for ap", but I get very strange values.

```python
cc = ampal.load_pdb("data/APH.pdb")
cc_eval = pacc.PACCAnalysis(cc)
print(cc_eval.generate_report())
```
<details>
 <summary>Output</summary>

```
Register Assignment
-------------------
defgabcdefgabcdefgabcdefgabcdefgabcdefga
LEEELKQLEEELQAIEEQLAQLQWKAQARKEKLAQLKEKL
LEEELKQLEEELQAIEEQLAQLQWKAQARKEKLAQLKEKL

Fit Quality - Mean Angular Discrepancy = 54.25 (Std Dev = 80.25)

Coiled Coil Parameters
----------------------
 Res#   Radius    Alpha  CrAngle
    1  +30.529  +59.150   -4.094
    2  +29.039  +60.957  +94.653
    3  +27.622  +62.827  +14.537
    4  +26.151  +64.865  -64.196
    5  +24.654  +69.249  +35.965
    6  +23.203  +72.976 +137.016
    7  +21.726  +66.770 -116.027
    8  +20.238  +68.305  -15.827
    9  +18.787  +74.746  +82.384
   10  +17.336  +74.234   +6.006
   11  +15.856  +71.319  -70.044
   12  +14.397  +75.708  +28.520
   13  +12.973  +79.890 +128.179
   14  +11.532  +78.676 -128.453
   15  +10.092  +79.886  -27.663
   16   +8.715  +84.085  +71.396
   17   +7.399  +86.550   -8.391
   18   +6.156  +87.714  -87.877
   19   +5.193  +89.461  +12.361
   20   +4.911  +90.293 +112.990
   21   +5.454  +89.728 -148.180
   22   +6.473  +86.676  -49.504
   23   +7.737  +84.222  +52.946
   24   +9.115  +84.020 +154.491
   25  +10.503  +80.605 -108.473
   26  +11.910  +75.504   -8.590
   27  +13.365  +76.341  +96.881
   28  +14.822  +76.757 -163.136
   29  +16.257  +71.077  -66.362
   30  +17.717  +67.692  +37.077
   31  +19.199  +71.723 +142.996
   32  +20.655  +70.122 -119.547
   33  +22.108  +63.452  -20.800
   34  +23.592  +64.620  +86.538
   35  +25.070  +68.340   +9.092
   36  +26.523  +65.119  -72.256
   37  +28.014  +63.220  +30.008
   38  +29.488  +61.428 +131.219
   39  +30.922  +59.343 -128.847
   40  +32.387   +0.000   +0.000
--------------------------------
  Ave  +17.696  +73.786   +1.461
Std D   +8.269   +9.197  +88.641

```

</details>

I guess `flip_reference_axis_if_antiparallel` should come in to play somewhere, but `ampal.analyse_protein.flip_reference_axis_if_antiparallel(cc_eval.cc[0], cc_eval.ra)` doesn't cut it :)

![image](https://user-images.githubusercontent.com/19926/41542435-3bbfbeba-7315-11e8-8311-d6d9889d7dc3.png)

(Here is the example pdb [APH.pdb.gz](https://github.com/isambard-uob/isambard/files/2111804/APH.pdb.gz))

**Comment by ChrisWellsWood** [comment]
I'll take a look, I haven't done much with this code in a while, unless @jackheal knows off the top of his head.

**Comment by ajasja** [comment]
Thanks! I'd also be interested in getting the z_shift (I guess it's just the distance between the correct C_alpha atoms projected onto the reference axis?).

**Comment by jackheal** [comment]
I don't know off the top of my head. @ChrisWellsWood let me know if you want me to have a more thorough look into it or have a chat together - it's been a while for both of us!

**Comment by ajasja** [comment]
@ChrisWellsWood Fixed for antiparallels as well.
https://github.com/isambard-uob/isambard/pull/8
